-- Création de la table CADEAU_CATEGORIE
CREATE TABLE CADEAU_CATEGORIE (
    ID_CATEGORIE INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CATEGORIE VARCHAR(100) NOT NULL
);

-- Création de la table CADEAU_CADEAU
CREATE TABLE CADEAU_CADEAU (
    ID_CADEAU INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CADEAU VARCHAR(100) NOT NULL,
    PRIX_CADEAU INT NOT NULL,
    SOLD BOOLEAN NOT NULL
);

CREATE TABLE CADEAU_PHOTO_CADEAU (
    ID_PHOTO_CADEAU INT AUTO_INCREMENT PRIMARY KEY,
    NOM_PHOTO VARCHAR(100) NOT NULL,
    ID_CADEAU INT NOT NULL,
    FOREIGN KEY (ID_CADEAU) REFERENCES CADEAU_CADEAU(ID_CADEAU)
);

-- Création de la table CADEAU_CATEGORIE_CADEAU
CREATE TABLE CADEAU_CATEGORIE_CADEAU (
    ID_CATEGORIE_CADEAU INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIE INT NOT NULL,
    ID_CADEAU INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIE) REFERENCES CADEAU_CATEGORIE(ID_CATEGORIE),
    FOREIGN KEY (ID_CADEAU) REFERENCES CADEAU_CADEAU(ID_CADEAU)
);

-- Création de la table CADEAU_USER
CREATE TABLE CADEAU_USER (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ADMIN BOOLEAN NOT NULL
);

-- Création de la table CADEAU_DEPOT
CREATE TABLE CADEAU_DEPOT (
    ID_DEPOT INT AUTO_INCREMENT PRIMARY KEY,
    VALEUR_DEPOT INT NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES CADEAU_USER(ID_USER)
);

-- Création de la table CADEAU_STATE
CREATE TABLE CADEAU_STATE (
    ID_STATE_EVENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_STATE VARCHAR(100) NOT NULL
);

-- Création de la table CADEAU_DEMANDE_DEPOT
CREATE TABLE CADEAU_DEMANDE_DEPOT (
    ID_DEPOT INT AUTO_INCREMENT PRIMARY KEY,
    VALEUR_DEPOT INT NOT NULL,
    ID_STATE_EVENT INT NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_STATE_EVENT) REFERENCES CADEAU_STATE(ID_STATE_EVENT),
    FOREIGN KEY (ID_USER) REFERENCES CADEAU_USER(ID_USER)
);

-- Création de la table CADEAU_TYPE_MOUVEMENT
CREATE TABLE CADEAU_TYPE_MOUVEMENT (
    ID_TYPE_MOUVEMENT INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL
);

-- Création de la table CADEAU_MOUVEMENT
CREATE TABLE CADEAU_MOUVEMENT (
    ID_MOUVEMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_TYPE_MOUVEMENT INT NOT NULL,
    DATE_MOUVEMENT DATE NOT NULL,
    FOREIGN KEY (ID_TYPE_MOUVEMENT) REFERENCES CADEAU_TYPE_MOUVEMENT(ID_TYPE_MOUVEMENT)
);

-- Création de la table CADEAU_CADEAU_MOUVEMENT
CREATE TABLE CADEAU_CADEAU_MOUVEMENT (
    ID_PRODUIT_MOUVEMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CADEAU INT NOT NULL,
    ID_MOUVEMENT INT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (ID_CADEAU) REFERENCES CADEAU_CADEAU(ID_CADEAU),
    FOREIGN KEY (ID_MOUVEMENT) REFERENCES CADEAU_MOUVEMENT(ID_MOUVEMENT)
);

-- Création de la table CADEAU_HISTORIQUE
CREATE TABLE CADEAU_HISTORIQUE (
    ID_HISTORIQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    ID_CADEAU_MOUVEMENT INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES CADEAU_USER(ID_USER),
    FOREIGN KEY (ID_CADEAU_MOUVEMENT) REFERENCES CADEAU_CADEAU_MOUVEMENT(ID_PRODUIT_MOUVEMENT)
);
